### ISSUE TITLE
Wrong shape in memory initializer & updater

### ISSUE THREAD

**Issue by YoPatapon** [jayleicn/recurrent-transformer#2]
Hi,

Thanks for sharing the code.
I found a small error in memory initializer & updater when using MART. The memory has shape `[N, L, intermediate_size]`, but the projection layers are from` hidden_size` to `hidden_size`. If `intermediate_size` and `hidden_size` are not equal, it will raise a wrong shape error.

**Comment by jayleicn** [comment]
Thanks! We did not notice this issue as we always use `intermediate_size == hidden_size`. A PR is welcome!
