### ISSUE TITLE
Function 'LogSoftmaxBackward' returned nan values in its 0th output.

### ISSUE THREAD

**Issue by lingshi0606** [jayleicn/recurrent-transformer#5]
First, the train.sh file have some problems that ${dset_name} should be ${model_type} in the Line 39 42 48 50.
But when the model_type is 'xl' or 'xlrg', I got the Error:

File "src/train.py", line 639, in <module>
   main()
 File "src/train.py", line 635, in main
   train(model, train_loader, val_loader, device, opt)
 File "src/train.py", line 330, in train
   model, training_data, optimizer, ema, device, opt, writer, epoch_i)
 File "src/train.py", line 78, in train_epoch
   input_masks_list, token_type_ids_list, input_labels_list)
 File "src/rtransformer/model.py", line 40, in forward
   output = self.log_softmax(output[valid_indices]) 
 
  Training =>:   0%|                                                                                                                                                                       | 0/313 [00:05<?, ?it/s]
Traceback (most recent call last):
  File "src/train.py", line 639, in <module>
    main()
  File "src/train.py", line 635, in main
    train(model, train_loader, val_loader, device, opt)
  File "src/train.py", line 330, in train
    model, training_data, optimizer, ema, device, opt, writer, epoch_i)
  File "src/train.py", line 131, in train_epoch
    loss.backward()
RuntimeError: Function 'LogSoftmaxBackward' returned nan values in its 0th output. 

Pls help me, thanks!

**Comment by jayleicn** [comment]
Hi @lingshi0606,

Thanks! I have fixed the `train.sh` script. I have successfully launched `bash scripts/train.sh yc2 xlrg` with PyTorch 1.1. It should be something wrong with your PyTorch version.   

Best,
Jie

**Comment by lingshi0606** [comment]
Hi, @jayleicn ,
My PyTorch version is 1.3.0&1.1.0, and I can launch ‘bash script/train.sh yc2 xlrg/xl/mtrans/mart’, and ‘bash script/train.sh anet mart/mtrans’, but ‘bash script/train.sh anet xl/xlrg’ gives me the error:

 ' RuntimeError: Function 'LogSoftmaxBackward' returned nan values in its 0th output. '

I can't fix the code... :(
Do you know what's wrong with it?

**Comment by jayleicn** [comment]
Hi @lingshi0606, I cannot reproduce this error on my end, so I'll use my best guess. It might be a gradient exploding problem? Since xlrg requires recurrent gradients, add an extra flag `--grad_clip 5` could potentially help.

**Comment by awkrail** [comment]
I met the same problem. I found that this problem occurs due to `r_w_bias` and `r_r_bias` have `nan` elements.
Thus, I replace them with `nn.Parameter(torch.zeros(config.num_attention_heads, self.d_head))` and it works.
```python
# self.r_w_bias = nn.Parameter(torch.Tensor(config.num_attention_heads, self.d_head))
self.r_w_bias = nn.Parameter(torch.zeros(config.num_attention_heads, self.d_head))
```
