### ISSUE TITLE
no such file or directory: model_tmp_greedy_val_lang.json

### ISSUE THREAD

**Issue by junchen14** [jayleicn/recurrent-transformer#6]
hi
thanks for your good work and sharing your code.

when I run your code today, I found that there are some errors during the training.  when I run the command "bash scripts/train.sh yc2 mart"
it gives me the error like the following:

File "/home/chenj0g/Desktop/mart/recurrent-transformer/src/utils.py", line 18, in load_json
    with open(file_path, "r") as f:
IOError: [Errno 2] No such file or directory: '/home/chenj0g/Desktop/mart/recurrent-transformer/results/yc2_re_init_2021_01_03_15_09_03/model_tmp_greedy_pred_val_lang.json'

do you know how could I solve this problem?

**Comment by jayleicn** [comment]
Hi @junchen14,

It looks like something is wrong with the coco evaluation part. You can try to directly use the cmd [here](https://github.com/jayleicn/recurrent-transformer/blob/master/src/train.py#L252-L254) in bash to see what the errors are. 

Best,
Jie

**Comment by zhipengLi116** [comment]
我也遇到了同样的问题，有人遇到这个并且解决了的吗
