### ISSUE TITLE
I cannot reduce the results on yc2. Can you share some parameters?

### ISSUE THREAD

**Issue by lingshi0606** [jayleicn/recurrent-transformer#7]
Hello, it is me too. I can reduce the results in your paper MART on anet. 
But the results on yc2 is CIDEr 23.46, not 35.74, Meteor 15.1, not 15.9 and the BLEU@4 is 6.88, not 8. 
Can you share some parameters different from the anet, which is beneficial for yc2 to a 30+ CIDEr?
Thanks very much.

**Comment by jayleicn** [comment]
Hi @lingshi0606,

As far as I remember, I used the default hyper-parameters in the [train.py](https://github.com/jayleicn/recurrent-transformer/blob/master/src/train.py) and [train.sh](https://github.com/jayleicn/recurrent-transformer/blob/master/scripts/train.sh) files. (In [train.sh](https://github.com/jayleicn/recurrent-transformer/blob/master/scripts/train.sh#L26), you can see dataset specific hyper-parameters for yc2.)

I am not sure why your results much lower. Is this result consistent across different random seeds?

Best,
Jie
