### ISSUE TITLE
Consultation on the experimental results in the paper

### ISSUE THREAD

**Issue by lszp** [jayleicn/recurrent-transformer#8]
Thank you for your code！
I have a question for you. Can you tell me whether the experimental results of other methods (eg, VTransformer, GVD, AdvInf) in Table 1 and table 2 are obtained from your own experiments or from the corresponding papers ？

**Comment by jayleicn** [comment]
Most of them are from the corresponding papers. I emailed the authors to obtain the predictions. You can take a look at Section 4.3 to see the details.

**Comment by lszp** [comment]
@jayleicn ，OK, thank you for your reply.

**Comment by ShiYaya** [comment]
> Most of them are from the corresponding papers. I emailed the authors to obtain the predictions. You can take a look at Section 4.3 to see the details.

Will you release the predictions in Tables 1 and 2?
I want to follow your work and do human evaluation use these predictions
